-- =============================================================================
-- RelicVault AI — Initial Schema
-- =============================================================================
-- Crowdsourced artifact submissions with AI tags, manual tags, and GPS
-- coordinates. Exact coordinates are stored for archival purposes but must
-- never be exposed to non-admin clients; blurred coordinates are computed
-- automatically and served through the artifacts_public view.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Custom types
-- ---------------------------------------------------------------------------

create type public.user_role as enum ('user', 'admin');

create type public.preservation_status as enum (
  'excellent',
  'good',
  'fair',
  'poor',
  'critical',
  'unknown'
);

-- ---------------------------------------------------------------------------
-- profiles
-- Linked 1:1 with auth.users. Stores public contributor metadata and role.
-- ---------------------------------------------------------------------------

create table public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  username    text unique not null,
  display_name text,
  avatar_url  text,
  bio         text,
  role        public.user_role not null default 'user',
  created_at  timestamptz not null default now(),

  constraint profiles_username_length check (char_length(username) between 3 and 30),
  constraint profiles_username_format check (username ~ '^[a-zA-Z0-9_-]+$')
);

comment on table public.profiles is
  'Public user profile linked to Supabase auth.users.';

comment on column public.profiles.role is
  'Admin users may read exact GPS coordinates; all others receive blurred values.';

create index profiles_username_idx on public.profiles (username);

-- ---------------------------------------------------------------------------
-- artifacts
-- Core submission record. exact_lat/exact_lng are admin-only at the API layer.
-- blurred_lat/blurred_lng are auto-computed by trigger on write.
-- ---------------------------------------------------------------------------

create table public.artifacts (
  id                   uuid primary key default gen_random_uuid(),
  title                text not null,
  description          text,
  image_url            text not null,
  ai_tags              text[] not null default '{}',
  manual_tags          text[] not null default '{}',
  era                  text,
  preservation_status  public.preservation_status not null default 'unknown',
  exact_lat            double precision,
  exact_lng            double precision,
  blurred_lat          double precision,
  blurred_lng          double precision,
  is_protected         boolean not null default false,
  created_at           timestamptz not null default now(),
  user_id              uuid not null references public.profiles (id) on delete cascade,

  constraint artifacts_title_not_empty check (char_length(trim(title)) > 0),
  constraint artifacts_image_url_not_empty check (char_length(trim(image_url)) > 0),
  constraint artifacts_exact_coords_pair check (
    (exact_lat is null and exact_lng is null)
    or (exact_lat is not null and exact_lng is not null)
  ),
  constraint artifacts_exact_lat_range check (
    exact_lat is null or (exact_lat >= -90 and exact_lat <= 90)
  ),
  constraint artifacts_exact_lng_range check (
    exact_lng is null or (exact_lng >= -180 and exact_lng <= 180)
  ),
  constraint artifacts_blurred_coords_pair check (
    (blurred_lat is null and blurred_lng is null)
    or (blurred_lat is not null and blurred_lng is not null)
  )
);

comment on table public.artifacts is
  'Artifact submissions with tags, preservation metadata, and GPS coordinates.';

comment on column public.artifacts.exact_lat is
  'Precise capture latitude. Never expose to non-admin clients.';

comment on column public.artifacts.exact_lng is
  'Precise capture longitude. Never expose to non-admin clients.';

comment on column public.artifacts.blurred_lat is
  'Privacy-safe latitude derived from exact_lat. Safe for public display.';

comment on column public.artifacts.blurred_lng is
  'Privacy-safe longitude derived from exact_lng. Safe for public display.';

comment on column public.artifacts.is_protected is
  'When true, applies a coarser blur to protect sensitive heritage sites.';

comment on column public.artifacts.ai_tags is
  'Tags generated by OpenAI analysis of the artifact image.';

comment on column public.artifacts.manual_tags is
  'Tags added manually by the contributor.';

create index artifacts_user_id_idx on public.artifacts (user_id);
create index artifacts_created_at_idx on public.artifacts (created_at desc);
create index artifacts_is_protected_idx on public.artifacts (is_protected);
create index artifacts_ai_tags_gin_idx on public.artifacts using gin (ai_tags);
create index artifacts_manual_tags_gin_idx on public.artifacts using gin (manual_tags);

-- ---------------------------------------------------------------------------
-- Helper: is_admin
-- Returns true when the given user (defaults to caller) has the admin role.
-- ---------------------------------------------------------------------------

create or replace function public.is_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = p_user_id
      and role = 'admin'
  );
$$;

comment on function public.is_admin is
  'Checks whether a user holds the admin role. Used by views and server logic.';

-- ---------------------------------------------------------------------------
-- Helper: blur_coordinates
-- Rounds coordinates to reduce precision. Protected sites get a coarser blur.
--   Standard : 2 decimal places (~1.1 km)
--   Protected: 1 decimal place  (~11 km)
-- ---------------------------------------------------------------------------

create or replace function public.blur_coordinates(
  p_lat         double precision,
  p_lng         double precision,
  p_is_protected boolean default false
)
returns table (blurred_lat double precision, blurred_lng double precision)
language plpgsql
immutable
as $$
declare
  v_precision integer;
begin
  if p_lat is null or p_lng is null then
    return query select null::double precision, null::double precision;
    return;
  end if;

  v_precision := case when p_is_protected then 1 else 2 end;

  return query
  select
    round(p_lat::numeric, v_precision)::double precision,
    round(p_lng::numeric, v_precision)::double precision;
end;
$$;

comment on function public.blur_coordinates is
  'Derives privacy-safe coordinates from exact GPS values.';

-- ---------------------------------------------------------------------------
-- Trigger: auto-blur coordinates on insert / update
-- ---------------------------------------------------------------------------

create or replace function public.set_blurred_coordinates()
returns trigger
language plpgsql
as $$
declare
  v_blur record;
begin
  if new.exact_lat is not null and new.exact_lng is not null then
    select * into v_blur
    from public.blur_coordinates(new.exact_lat, new.exact_lng, new.is_protected);

    new.blurred_lat := v_blur.blurred_lat;
    new.blurred_lng := v_blur.blurred_lng;
  else
    new.blurred_lat := null;
    new.blurred_lng := null;
  end if;

  return new;
end;
$$;

create trigger artifacts_blur_coordinates
  before insert or update of exact_lat, exact_lng, is_protected
  on public.artifacts
  for each row
  execute function public.set_blurred_coordinates();

-- ---------------------------------------------------------------------------
-- Trigger: auto-create profile on auth signup
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'username',
      'user_' || substr(replace(new.id::text, '-', ''), 1, 8)
    ),
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- View: artifacts_public
-- Safe read surface for clients. Non-admins never see exact_lat / exact_lng.
-- Admins receive exact coordinates in the display_lat / display_lng columns.
-- ---------------------------------------------------------------------------

create or replace view public.artifacts_public
with (security_invoker = true)
as
select
  a.id,
  a.title,
  a.description,
  a.image_url,
  a.ai_tags,
  a.manual_tags,
  a.era,
  a.preservation_status,
  case
    when public.is_admin() then a.exact_lat
    else a.blurred_lat
  end as display_lat,
  case
    when public.is_admin() then a.exact_lng
    else a.blurred_lng
  end as display_lng,
  a.is_protected,
  a.created_at,
  a.user_id
from public.artifacts a;

comment on view public.artifacts_public is
  'Privacy-safe artifact reads. Query this view from the client instead of the base table.';

-- ---------------------------------------------------------------------------
-- Row Level Security — profiles
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;

-- Anyone (including anonymous) can browse profiles
create policy "Profiles are viewable by everyone"
  on public.profiles
  for select
  to anon, authenticated
  using (true);

-- Users may update only their own profile (cannot self-promote to admin)
create policy "Users can update their own profile"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (
    auth.uid() = id
    and role = (select p.role from public.profiles p where p.id = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- Row Level Security — artifacts
-- ---------------------------------------------------------------------------

alter table public.artifacts enable row level security;

-- Any user (anonymous or authenticated) can read all artifacts
create policy "Artifacts are viewable by everyone"
  on public.artifacts
  for select
  to anon, authenticated
  using (true);

-- Authenticated users may insert artifacts they own
create policy "Authenticated users can insert their own artifacts"
  on public.artifacts
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Owners may update their own submissions
create policy "Users can update their own artifacts"
  on public.artifacts
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Owners may delete their own submissions
create policy "Users can delete their own artifacts"
  on public.artifacts
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Grants
-- Revoke direct SELECT on the base artifacts table from client roles so that
-- exact_lat / exact_lng cannot leak through PostgREST. Client reads go through
-- artifacts_public; writes go to the base table via RLS policies above.
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;

grant select on public.profiles to anon, authenticated;
grant update on public.profiles to authenticated;

grant insert, update, delete on public.artifacts to authenticated;
grant select on public.artifacts_public to anon, authenticated;

revoke select on public.artifacts from anon, authenticated;

-- Service role retains full access for server-side jobs and admin tooling.
grant all on public.profiles to service_role;
grant all on public.artifacts to service_role;
grant select on public.artifacts_public to service_role;
